package controlevendas.view;

/**
 *
 * @author lucas
 */
public class JFDashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFDashboard
     */
    public JFDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbVendasQtd = new javax.swing.JButton();
        jbUsuariosQtd = new javax.swing.JButton();
        jbProdutosQtd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtUltimosClientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVendasRecentes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setAutoscrolls(true);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbVendasQtd.setBackground(new java.awt.Color(255, 139, 14));
        jbVendasQtd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbVendasQtd.setForeground(new java.awt.Color(255, 255, 255));
        jbVendasQtd.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/ads/3-semestre/Natal-ed2/ProjetoControleVendas/img/cart.png")); // NOI18N
        jbVendasQtd.setText("VENDAS");
        jbVendasQtd.setFocusPainted(false);
        jbVendasQtd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbVendasQtd.setIconTextGap(12);
        jbVendasQtd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbVendasQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVendasQtdActionPerformed(evt);
            }
        });
        getContentPane().add(jbVendasQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 280, 140));

        jbUsuariosQtd.setBackground(new java.awt.Color(14, 104, 255));
        jbUsuariosQtd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbUsuariosQtd.setForeground(new java.awt.Color(255, 255, 255));
        jbUsuariosQtd.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/ads/3-semestre/Natal-ed2/ProjetoControleVendas/img/users.png")); // NOI18N
        jbUsuariosQtd.setText("USUARIOS");
        jbUsuariosQtd.setFocusPainted(false);
        jbUsuariosQtd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbUsuariosQtd.setIconTextGap(12);
        jbUsuariosQtd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbUsuariosQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUsuariosQtdActionPerformed(evt);
            }
        });
        getContentPane().add(jbUsuariosQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 280, 140));

        jbProdutosQtd.setBackground(new java.awt.Color(39, 182, 118));
        jbProdutosQtd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbProdutosQtd.setForeground(new java.awt.Color(255, 255, 255));
        jbProdutosQtd.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/ads/3-semestre/Natal-ed2/ProjetoControleVendas/img/produto.png")); // NOI18N
        jbProdutosQtd.setText("PRODUTOS");
        jbProdutosQtd.setFocusPainted(false);
        jbProdutosQtd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbProdutosQtd.setIconTextGap(12);
        jbProdutosQtd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbProdutosQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutosQtdActionPerformed(evt);
            }
        });
        getContentPane().add(jbProdutosQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 280, 140));

        jtUltimosClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Email Cliente", "Total", "Descricao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtUltimosClientes.setRowHeight(30);
        jtUltimosClientes.setShowGrid(true);
        jScrollPane1.setViewportView(jtUltimosClientes);
        if (jtUltimosClientes.getColumnModel().getColumnCount() > 0) {
            jtUltimosClientes.getColumnModel().getColumn(0).setResizable(false);
            jtUltimosClientes.getColumnModel().getColumn(1).setResizable(false);
            jtUltimosClientes.getColumnModel().getColumn(2).setResizable(false);
            jtUltimosClientes.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 1020, 140));

        jtVendasRecentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Email Cliente", "Total", "Descricao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVendasRecentes.setRowHeight(30);
        jtVendasRecentes.setShowGrid(true);
        jScrollPane2.setViewportView(jtVendasRecentes);
        if (jtVendasRecentes.getColumnModel().getColumnCount() > 0) {
            jtVendasRecentes.getColumnModel().getColumn(0).setResizable(false);
            jtVendasRecentes.getColumnModel().getColumn(1).setResizable(false);
            jtVendasRecentes.getColumnModel().getColumn(2).setResizable(false);
            jtVendasRecentes.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 1020, 140));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Últimos Clientes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Vendas Recentes");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVendasQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVendasQtdActionPerformed
      
    }//GEN-LAST:event_jbVendasQtdActionPerformed

    private void jbUsuariosQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUsuariosQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbUsuariosQtdActionPerformed

    private void jbProdutosQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutosQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbProdutosQtdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbProdutosQtd;
    private javax.swing.JButton jbUsuariosQtd;
    private javax.swing.JButton jbVendasQtd;
    private javax.swing.JTable jtUltimosClientes;
    private javax.swing.JTable jtVendasRecentes;
    // End of variables declaration//GEN-END:variables
}
