package controlevendas.view;

import controlevendas.data.UsuarioData;
import controlevendas.model.Usuario;
import controlevendas.utils.UtilsFrontEnd;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        initComponents();
        setStylesManual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtpSenha = new javax.swing.JPasswordField();
        jbEntrar = new javax.swing.JButton();
        jlLoginInvalido = new javax.swing.JLabel();
        checkboxVerSenha = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jlSenhaDigitada = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfEmail.setBackground(new java.awt.Color(255, 255, 255));
        jtfEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 104, 255), 3));
        jtfEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 420, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 104, 255));
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(14, 104, 255));
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(14, 104, 255));
        jLabel3.setText("Esqueceu sua senha?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jtpSenha.setBackground(new java.awt.Color(255, 255, 255));
        jtpSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 104, 255), 3));
        jtpSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpSenhaActionPerformed(evt);
            }
        });
        jtpSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtpSenhaKeyReleased(evt);
            }
        });
        getContentPane().add(jtpSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 390, 40));

        jbEntrar.setBackground(new java.awt.Color(14, 104, 255));
        jbEntrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jbEntrar.setText("ENTRAR");
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 420, 50));

        jlLoginInvalido.setBackground(new java.awt.Color(255, 255, 255));
        jlLoginInvalido.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jlLoginInvalido.setForeground(new java.awt.Color(255, 51, 51));
        jlLoginInvalido.setText("Email ou senha inválidos, tente novamente!");
        getContentPane().add(jlLoginInvalido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        checkboxVerSenha.setBackground(new java.awt.Color(255, 255, 255));
        checkboxVerSenha.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/ads/3-semestre/Natal-ed2/ProjetoControleVendas/img/icon-view-password.png")); // NOI18N
        checkboxVerSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkboxVerSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(checkboxVerSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 40, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(14, 104, 255));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jlSenhaDigitada.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jlSenhaDigitada.setForeground(new java.awt.Color(14, 104, 255));
        jlSenhaDigitada.setText("Sua senha está vazia");
        getContentPane().add(jlSenhaDigitada, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/lucas/NetBeansProjects/ads/3-semestre/Natal-ed2/ProjetoControleVendas/img/logout.png")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 70, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    /****************************************************
     * CLIQUE NO BOTAO ENTRAR
    ****************************************************/
    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
        try {
            UsuarioData daoDataUser = new UsuarioData();
            Usuario objUser = daoDataUser.login(jtfEmail.getText(), jtpSenha.getText());
            
            if(objUser != null) {
                new JFPrincipal(objUser).setVisible(true);
                dispose();
                return;
            }
            
            // EXIBINDO MENSAGEM DE LOGIN INVALIDO COM INTERVALO DE EXIBICAO
            jlLoginInvalido.setVisible(true);
            UtilsFrontEnd.setTimeout(() -> {
                jlLoginInvalido.setVisible(false);
            }, 2500);
        } catch (Exception ex) { 
            System.err.println("ERROR: "+ex); // MENSAGEM DO ERRO NO CONSOLE
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro ao buscar o usuário. Verifique seus dados e tente novamente!", 
                                                "Erro ao fazer login", JOptionPane.ERROR_MESSAGE); // MENSAGEM EXIBIDA AO USUARIO
        }
    }//GEN-LAST:event_jbEntrarActionPerformed

    private void jtpSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtpSenhaActionPerformed

    
    /****************************************************
     * CLIQUE NO CHECKBOX DE VER SENHA
     ****************************************************/
    private void checkboxVerSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkboxVerSenhaMouseClicked
        // VERIFICANDO SE O CHECKBOX ESTÁ CHECKADO
        if(!checkboxVerSenha.isSelected()) {
            jlSenhaDigitada.setVisible(false);
            return;
        }
        
        jlSenhaDigitada.setText(jtpSenha.getText());
        jlSenhaDigitada.setVisible(true);
    }//GEN-LAST:event_checkboxVerSenhaMouseClicked

    /****************************************************
     * TECLA O TECLADO
     ****************************************************/
    private void jtpSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpSenhaKeyReleased
        jlSenhaDigitada.setText(jtpSenha.getText());
    }//GEN-LAST:event_jtpSenhaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkboxVerSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JLabel jlLoginInvalido;
    private javax.swing.JLabel jlSenhaDigitada;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JPasswordField jtpSenha;
    // End of variables declaration//GEN-END:variables

    /**************************************************
     * FUNCOES PERSONLIZADAS
     *************************************************/
    private void setStylesManual() {
        jlLoginInvalido.setVisible(false);
        jlSenhaDigitada.setVisible(false);
    }
}