package controlevendas.view;

import controlevendas.model.Usuario;
import controlevendas.utils.UtilsFrontEnd;
import java.awt.Color;

/**
 *
 * @author lucas
 */
public class JFPrincipal extends javax.swing.JFrame {
    private Usuario objUser;

    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
        setStylesManual();
        
        this.objUser = new Usuario();
    }

    public JFPrincipal(Usuario objUser) {
        this();
        this.objUser = objUser;
        jlCodigoAdmin.setText(""+objUser.getCod());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jbClientes = new javax.swing.JButton();
        jbDashboard = new javax.swing.JButton();
        jbPedidos = new javax.swing.JButton();
        jbProdutos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbSair = new javax.swing.JButton();
        jbCategoria = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlCodigoAdmin = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(46, 55, 64));
        setMinimumSize(new java.awt.Dimension(1400, 950));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jdpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1100, 950));

        jbClientes.setBackground(new java.awt.Color(43, 42, 42));
        jbClientes.setForeground(new java.awt.Color(255, 255, 255));
        jbClientes.setText("      USUÁRIOS");
        jbClientes.setBorder(null);
        jbClientes.setBorderPainted(false);
        jbClientes.setBorderPainted(false);
        jbClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbClientes.setFocusable(false);
        jbClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbClientes.setMargin(new java.awt.Insets(25, 14, 2, 14));
        jbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jbClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 310, 47));

        jbDashboard.setBackground(new java.awt.Color(14, 104, 255));
        jbDashboard.setForeground(new java.awt.Color(255, 255, 255));
        jbDashboard.setText("        DASHBOARD");
        jbDashboard.setBorder(null);
        jbDashboard.setBorderPainted(false);
        jbDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbDashboard.setFocusPainted(false);
        jbDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDashboardActionPerformed(evt);
            }
        });
        getContentPane().add(jbDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 320, 47));

        jbPedidos.setBackground(new java.awt.Color(43, 42, 42));
        jbPedidos.setForeground(new java.awt.Color(255, 255, 255));
        jbPedidos.setText("      PEDIDOS");
        jbPedidos.setBorder(null);
        jbPedidos.setBorderPainted(false);
        jbPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbPedidos.setFocusable(false);
        jbPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbPedidos.setMargin(new java.awt.Insets(25, 14, 2, 14));
        jbPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(jbPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 310, 47));

        jbProdutos.setBackground(new java.awt.Color(43, 42, 42));
        jbProdutos.setForeground(new java.awt.Color(255, 255, 255));
        jbProdutos.setText("      PRODUTOS");
        jbProdutos.setBorder(null);
        jbProdutos.setBorderPainted(false);
        jbProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbProdutos.setFocusable(false);
        jbProdutos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbProdutos.setMargin(new java.awt.Insets(25, 14, 2, 14));
        jbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(jbProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 310, 47));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGOTIPO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jbSair.setBackground(new java.awt.Color(14, 104, 255));
        jbSair.setForeground(new java.awt.Color(255, 255, 255));
        jbSair.setText("   Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });
        getContentPane().add(jbSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 840, 230, 70));

        jbCategoria.setBackground(new java.awt.Color(43, 42, 42));
        jbCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jbCategoria.setText("      CATEGORIAS");
        jbCategoria.setBorder(null);
        jbCategoria.setBorderPainted(false);
        jbCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbCategoria.setFocusable(false);
        jbCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbCategoria.setMargin(new java.awt.Insets(25, 14, 2, 14));
        jbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(jbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 310, 47));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo do Administrador:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, -1, -1));

        jlCodigoAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jlCodigoAdmin.setText("0");
        getContentPane().add(jlCodigoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 780, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClientesActionPerformed
        JFUsuario objUsuario = new JFUsuario();
        jdpPrincipal.add(objUsuario);
        objUsuario.setVisible(true);        
    }//GEN-LAST:event_jbClientesActionPerformed

    private void jbDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDashboardActionPerformed
        JFDashboard objDashboard = new JFDashboard();
        jdpPrincipal.add(objDashboard);
        objDashboard.setVisible(true);
    }//GEN-LAST:event_jbDashboardActionPerformed

    private void jbPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedidosActionPerformed
        JFPedido objPedido = new JFPedido();
        jdpPrincipal.add(objPedido);
        objPedido.setVisible(true);
    }//GEN-LAST:event_jbPedidosActionPerformed

    
    /*************************************************************
     * CLIQUE NO BOTÃO DE PRODUTOS
     **************************************************************/
    private void jbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProdutosActionPerformed
       JFProduto objCadastroProduto = new JFProduto();
       jdpPrincipal.add(objCadastroProduto);
       objCadastroProduto.setVisible(true);
    }//GEN-LAST:event_jbProdutosActionPerformed

    /*************************************************************
     * CLIQUE NO BOTÃO SAIR
     **************************************************************/
    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    /*************************************************************
     * CLIQUE NO BOTÃO DE CATEGORIAS
     **************************************************************/
    private void jbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCategoriaActionPerformed
        JFCategoria objCadastroCategoria = new JFCategoria();
        jdpPrincipal.add(objCadastroCategoria);
        objCadastroCategoria.setVisible(true);
    }//GEN-LAST:event_jbCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JButton jbCategoria;
    private javax.swing.JButton jbClientes;
    private javax.swing.JButton jbDashboard;
    private javax.swing.JButton jbPedidos;
    private javax.swing.JButton jbProdutos;
    private javax.swing.JButton jbSair;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JLabel jlCodigoAdmin;
    // End of variables declaration//GEN-END:variables


    /***********************************************
     * ESTILOS MANUAIS
     *********************************************/
    private void setStylesManual() {
        getContentPane().setBackground(Color.decode("#2b2a2a"));
        
        UtilsFrontEnd.removeBackground(jbClientes);
        UtilsFrontEnd.removeBackground(jbProdutos);
        UtilsFrontEnd.removeBackground(jbPedidos);
        UtilsFrontEnd.removeBackground(jbCategoria);
    }

}
